name: blip_client_platform_interface
description: A common platform interface for the blip_client plugin.
author: Mateus Freitas (mateus@blubybs2.com)
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
version: 0.0.2

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^1.0.0
  equatable: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.4.0-dev.d210.1
  mockito: ^4.1.3

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: "<=1.22.6"
