name: blip_client_platform_interface
description: A common platform interface for the blip_client plugin.
author: Mateus Freitas (mateus@blubybs2.com)
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^1.0.3
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  effective_dart: ^1.3.0

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"