name: blip_client_platform_interface
description: A common platform interface for the blip_client plugin.
author: Mateus Freitas (mateus@blubybs2.com)
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
version: 0.0.3

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.6.0
  mocktail: ^0.1.4

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.22.5"
