name: blip_client
description: A new flutter plugin project.
author: Mateus Freitas (mateus@blubybs2.com)
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
version: 0.0.2

dependencies:
  flutter:
    sdk: flutter
  
  blip_client_platform_interface:
    git:
      url: https://github.com/mateusfsilva/blip_client_flutter.git
      ref: 57247912871a90ec42a059682c0aa84dfda9abd0
      path: blip_client_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.4.0-dev.d210.1

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: "<=1.22.6"

flutter:
  plugin:
    platforms:
      android:
        package: com.blubybs2.blip_client
        pluginClass: BlipClientPlugin
      ios:
        pluginClass: BlipClientPlugin
