name: blip_client
description: A new flutter plugin project.
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
version: 0.0.3

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  
  blip_client_platform_interface:
    git:
      url: https://github.com/mateusfsilva/blip_client_flutter.git
      ref: 3ca0eaf3cb4977a17c98963864bb3b01f9967d3c
      path: blip_client_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.22.5"

flutter:
  plugin:
    platforms:
      android:
        package: com.blubybs2.blip_client
        pluginClass: BlipClientPlugin
      ios:
        pluginClass: BlipClientPlugin
