name: blip_client
description: A new flutter plugin project.
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
version: 0.0.4

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  
  blip_client_platform_interface:
    git:
      url: https://github.com/mateusfsilva/blip_client_flutter.git
      ref: e8dff8af84b9d1840119effdc0659dd07af7fde4
      path: blip_client_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.8.2

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.22.5"

flutter:
  plugin:
    platforms:
      android:
        package: com.blubybs2.blip_client
        pluginClass: BlipClientPlugin
      ios:
        pluginClass: BlipClientPlugin
