name: blip_client
description: A new flutter plugin project.
repository: https://github.com/mateusfsilva
issue_tracker: https://github.com/mateusfsilva/<repository>/issues
publish_to: none
version: 0.0.6

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  
  blip_client_platform_interface:
    git:
      url: https://github.com/mateusfsilva/blip_client_flutter.git
      ref: 53d6ad99a6e73183eef8c1e18d3f29aef9e223a8
      path: blip_client_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.10.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.5"

flutter:
  plugin:
    platforms:
      android:
        package: com.blubybs2.blip_client
        pluginClass: BlipClientPlugin
      ios:
        pluginClass: BlipClientPlugin
