include: package:lint/analysis_options.yaml

strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    lines_longer_than_80_chars: true
    sort_constructors_first: true
    always_put_control_body_on_new_line: true
    sort_pub_dependencies: false
