name: blip_client_example
description: Demonstrates how to use the blip_client plugin.
number: 1.1.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

dependencies:
  flutter:
    sdk: flutter

  blip_client:
    # When depending on this package from a real application you should use:
    #   blip_client: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  lint: ^1.10.0

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.5"

flutter:
  uses-material-design: true
